In [1]:
import numpy as np
import pandas as pd

In [2]:
df_base = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep = ';', encoding = 'latin1')
df_base

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36213,159,5,2025,2025m05,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,3.0,0.0,24,1,0,0,0,0,150,2
36214,165,5,2025,2025m05,33,5,Mangaratiba,3302601,Interior,1,...,7.0,0.0,29,2,0,0,0,0,208,2
36215,166,5,2025,2025m05,33,5,Angra dos Reis,3300100,Interior,3,...,14.0,1.0,59,2,0,0,0,0,580,2
36216,167,5,2025,2025m05,43,5,Paraty,3303807,Interior,3,...,6.0,0.0,37,0,0,0,0,0,230,2
36217,168,5,2025,2025m05,28,5,Rio Claro,3304409,Interior,1,...,1.0,0.0,7,1,0,0,0,0,62,2

In [10]:
df_rj = df_base[['roubo_veiculo','furto_veiculos','cisp']]
df_rj

       roubo_veiculo  furto_veiculos  cisp
0                  5              12     1
1                  9               9     4
2                 11              28     5
3                 27              17     6
4                 23              12     7
...              ...             ...   ...
36213              0               2   159
36214              0               2   165
36215              0               4   166
36216              0               3   167
36217              0               1   168

[36218 rows x 3 columns]

In [11]:
df_del= df_base.groupby('Rio de Janeiro')['roubo_veiculo','furto_veiculos'].sum().reset_index()
df_del

KeyError: 'Rio de Janeiro'