In [15]:
import pandas as pd
import numpy as np

In [22]:
df_base = pd.read_csv('https://www.ispdados.rj.gov.br/Arquivos/BaseDPEvolucaoMensalCisp.csv', sep = ';', encoding = 'latin1')
df_base

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
0,1,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,0,...,NaN,NaN,21,2,0,0,0,0,578,3
1,4,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,15,6,0,1,0,0,441,3
2,5,1,2003,2003m01,5,1,Rio de Janeiro,3304557,Capital,3,...,NaN,NaN,47,2,1,0,0,0,637,3
3,6,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,6,...,NaN,NaN,26,2,1,0,0,0,473,3
4,7,1,2003,2003m01,1,1,Rio de Janeiro,3304557,Capital,4,...,NaN,NaN,10,1,3,0,0,0,147,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
36076,159,4,2025,2025m04,35,4,Cachoeiras de Macacu,3300803,Interior,0,...,6.0,0.0,18,1,0,0,0,0,117,2
36077,165,4,2025,2025m04,33,5,Mangaratiba,3302601,Interior,2,...,4.0,1.0,33,1,0,0,0,0,221,2
36078,166,4,2025,2025m04,33,5,Angra dos Reis,3300100,Interior,3,...,6.0,2.0,57,2,0,0,0,0,570,2
36079,167,4,2025,2025m04,43,5,Paraty,3303807,Interior,1,...,6.0,0.0,27,1,0,0,0,0,233,2
36080,168,4,2025,2025m04,28,5,Rio Claro,3304409,Interior,0,...,1.0,0.0,14,3,0,0,0,0,55,2

In [47]:
metropolitana = ['Belford Roxo', 'Cachoeiras de Macacu', 'Duque de Caxias', 'Guapimirim', 'Itaboraí', 'Itaguaí', 'Japeri', 'Magé', 'Maricá', 'Mesquita', 'Nilópolis', 'Niterói', 'Nova Iguaçu', 'Paracambi', 'Petrópolis', 'Queimados', 'Rio Bonito', 'Rio de Janeiro', 'São Gonçalo', 'São João de Meriti','Tanguá']

In [48]:
df_agora = df_base.loc[(df_base['ano'] == 2024) & (df_base['munic'].isin(metropolitana))]
df_agora

,cisp,mes,ano,mes_ano,aisp,risp,munic,mcirc,regiao,hom_doloso,...,cmp,cmba,ameaca,pessoas_desaparecidas,encontro_cadaver,encontro_ossada,pol_militares_mortos_serv,pol_civis_mortos_serv,registro_ocorrencias,fase
33889,1,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,16.0,4.0,12,0,0,0,0,0,889,3
33890,4,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,8.0,6.0,13,3,0,0,0,0,728,3
33891,5,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,12.0,2.0,46,3,0,0,0,0,1441,3
33892,6,1,2024,2024m01,4,1,Rio de Janeiro,3304557,Capital,0,...,2.0,1.0,23,2,0,0,0,0,650,3
33893,7,1,2024,2024m01,5,1,Rio de Janeiro,3304557,Capital,0,...,0.0,0.0,12,2,0,0,0,0,240,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35467,82,12,2024,2024m12,12,4,Maricá,3302700,Grande NiterÃÂÃÂÃÂÃÂ³i,2,...,11.0,0.0,115,5,0,0,0,0,1076,3
35483,105,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,11.0,0.0,75,3,0,0,0,0,782,3
35484,106,12,2024,2024m12,26,7,Petrópolis,3303906,Interior,0,...,7.0,1.0,42,3,0,0,0,0,354,3
35492,119,12,2024,2024m12,35,4,Rio Bonito,3304300,Interior,1,...,0.0,0.0,20,0,0,0,0,0,178,3
35528,159,12,2024,2024m12,35,4,Cachoeiras de Macacu,3300803,Interior,1,...,1.0,0.0,27,2,0,0,0,0,137,3

In [49]:
df_rj= df_agora.groupby('munic')['furto_celular'].sum().reset_index()
df_rj

                   munic  furto_celular
0           Belford Roxo            176
1   Cachoeiras de Macacu             17
2        Duque de Caxias            654
3             Guapimirim             43
4               Itaboraí            119
5                Itaguaí            189
6                 Japeri             29
7                   Magé            188
8                 Maricá            204
9               Mesquita             96
10             Nilópolis            171
11               Niterói           1229
12           Nova Iguaçu            635
13             Paracambi             31
14            Petrópolis            288
15             Queimados             67
16            Rio Bonito             36
17        Rio de Janeiro          29422
18           São Gonçalo            623
19    São João de Meriti            242
20                Tanguá             16

In [54]:
array_rj = np.array(df_rj['furto_celular'])
array_rj

array([  176,    17,   654,    43,   119,   189,    29,   188,   204,
          96,   171,  1229,   635,    31,   288,    67,    36, 29422,
         623,   242,    16])

In [56]:
media= np.mean(array_rj)
media

np.float64(1641.6666666666667)

In [57]:
mediana= np.median(array_rj)
mediana

np.float64(176.0)

In [58]:
distancia= (media - mediana)/(mediana)
distancia

np.float64(8.327651515151516)