In [1]:
print('oi')

oi

In [3]:
import pandas as pd

In [5]:
dados = [
['Ana', 23, 'São Paulo'],
['Bruno', 35, 'Rio de Janeiro'],
['Carlos', 45, 'Belo Horizonte'],
['Daniela', 29, 'Curitiba']
]

colunas = ['Nome', 'Idade', 'Cidade']

df = pd.DataFrame(dados, columns=colunas)
df

      Nome  Idade          Cidade
0      Ana     23       São Paulo
1    Bruno     35  Rio de Janeiro
2   Carlos     45  Belo Horizonte
3  Daniela     29        Curitiba

In [6]:
dict = {
'Nome': ['Eduardo', 'Fernanda', 'Gabriel', 
'Helena'],
'Idade': [32, 27, 41, 36],
'Cidade': ['Porto Alegre', 'Salvador', 'Fortaleza', 
'Recife']
}
df = pd.DataFrame(dict)
df

       Nome  Idade        Cidade
0   Eduardo     32  Porto Alegre
1  Fernanda     27      Salvador
2   Gabriel     41     Fortaleza
3    Helena     36        Recife

In [4]:
df = pd.read_csv('2º_2024.csv', sep = ';')
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',','.').astype(float)
print(df['Valor de Venda'].dtype)
df.head()

float64

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,01/07/2024,6.79,NaN,R$ / litro,VIBRA
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,01/07/2024,6.84,NaN,R$ / litro,VIBRA
2,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,DIESEL,01/07/2024,6.99,NaN,R$ / litro,VIBRA
3,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,DIESEL S10,01/07/2024,6.99,NaN,R$ / litro,VIBRA
4,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,ETANOL,01/07/2024,4.69,NaN,R$ / litro,VIBRA

In [5]:
df.tail(5)

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
421377,CO,GO,FORMOSA,PARANA DE FORA COMERCIO DE COMBUSTIVEIS E LUBR...,48.113.920/0001-42,AVENIDA A,SN,LOTE 7-A QUADRA88,PARQUE DA COLINA II,73808-192,GASOLINA,31/12/2024,"6,39",NaN,R$ / litro,ALE
421378,CO,GO,FORMOSA,PARANA DE FORA COMERCIO DE COMBUSTIVEIS E LUBR...,48.113.920/0001-42,AVENIDA A,SN,LOTE 7-A QUADRA88,PARQUE DA COLINA II,73808-192,GASOLINA ADITIVADA,31/12/2024,"6,39",NaN,R$ / litro,ALE
421379,CO,GO,FORMOSA,PARANA DE FORA COMERCIO DE COMBUSTIVEIS E LUBR...,48.113.920/0001-42,AVENIDA A,SN,LOTE 7-A QUADRA88,PARQUE DA COLINA II,73808-192,DIESEL,31/12/2024,"6,19",NaN,R$ / litro,ALE
421380,CO,GO,FORMOSA,PARANA DE FORA COMERCIO DE COMBUSTIVEIS E LUBR...,48.113.920/0001-42,AVENIDA A,SN,LOTE 7-A QUADRA88,PARQUE DA COLINA II,73808-192,DIESEL S10,31/12/2024,"6,34",NaN,R$ / litro,ALE
421381,CO,GO,FORMOSA,PARANA DE FORA COMERCIO DE COMBUSTIVEIS E LUBR...,48.113.920/0001-42,AVENIDA A,SN,LOTE 7-A QUADRA88,PARQUE DA COLINA II,73808-192,ETANOL,31/12/2024,"4,39",NaN,R$ / litro,ALE

In [6]:
df.info() # Informações gerais

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 421382 entries, 0 to 421381
Data columns (total 16 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   Regiao - Sigla     421382 non-null  object
 1   Estado - Sigla     421382 non-null  object
 2   Municipio          421382 non-null  object
 3   Revenda            421382 non-null  object
 4   CNPJ da Revenda    421382 non-null  object
 5   Nome da Rua        421382 non-null  object
 6   Numero Rua         421282 non-null  object
 7   Complemento        94698 non-null   object
 8   Bairro             420809 non-null  object
 9   Cep                421382 non-null  object
 10  Produto            421382 non-null  object
 11  Data da Coleta     421382 non-null  object
 12  Valor de Venda     421382 non-null  object
 13  Valor de Compra    0 non-null       float64
 14  Unidade de Medida  421382 non-null  object
 15  Bandeira           421382 non-null  object
dtypes: float64(1), object(15)
memory usage: 51.4+ MB

In [21]:
df.describe() # Estatísticas descritivas

       Valor de Venda  Valor de Compra
count   421382.000000              0.0
mean         5.684103              NaN
std          0.888075              NaN
min          2.990000              NaN
25%          5.480000              NaN
50%          5.970000              NaN
75%          6.260000              NaN
max          9.790000              NaN

In [8]:
df.shape # Dimensões (linhas, colunas)

(421382, 16)

In [9]:
df.columns # Lista de colunas

Index(['Regiao - Sigla', 'Estado - Sigla', 'Municipio', 'Revenda',
       'CNPJ da Revenda', 'Nome da Rua', 'Numero Rua', 'Complemento', 'Bairro',
       'Cep', 'Produto', 'Data da Coleta', 'Valor de Venda', 'Valor de Compra',
       'Unidade de Medida', 'Bandeira'],
      dtype='object')

In [10]:
df.iloc[0:3] # Acesso por índice

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,01/07/2024,"6,79",NaN,R$ / litro,VIBRA
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,01/07/2024,"6,84",NaN,R$ / litro,VIBRA
2,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,DIESEL,01/07/2024,"6,99",NaN,R$ / litro,VIBRA

In [ ]:
df.sort_values(by='') # Ordenar por idade

In [8]:
df_RJ = df.loc[(df['Estado - Sigla'] == 'RJ') & (df['Bairro'] == 'IRAJA')] # Acesso por condição
df_RJ.head()

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
39225,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA VARONEL LTDA,05.143.832/0001-80,RUA MONSENHOR FELIX,682,NaN,IRAJA,21235-110,DIESEL,16/07/2024,5.99,NaN,R$ / litro,BRANCA
39226,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA VARONEL LTDA,05.143.832/0001-80,RUA MONSENHOR FELIX,682,NaN,IRAJA,21235-110,GASOLINA,16/07/2024,5.59,NaN,R$ / litro,BRANCA
39227,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA VARONEL LTDA,05.143.832/0001-80,RUA MONSENHOR FELIX,682,NaN,IRAJA,21235-110,ETANOL,16/07/2024,3.99,NaN,R$ / litro,BRANCA
103752,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA VARONEL LTDA,05.143.832/0001-80,RUA MONSENHOR FELIX,682,NaN,IRAJA,21235-110,GASOLINA,13/08/2024,5.59,NaN,R$ / litro,BRANCA
103753,SE,RJ,RIO DE JANEIRO,POSTO DE GASOLINA VARONEL LTDA,05.143.832/0001-80,RUA MONSENHOR FELIX,682,NaN,IRAJA,21235-110,DIESEL S10,13/08/2024,5.99,NaN,R$ / litro,BRANCA

In [27]:
dados = {
'Departamento': ['Vendas', 'Vendas', 'RH', 'RH', 'TI', 'TI'],
'Funcionário': ['Ana', 'Bruno', 'Carlos', 'Daniela', 'Eduardo', 
'Fernanda'],
'Salário': [3000, 3200, 2500, 2700, 4000, 4200]
}
df = pd.DataFrame(dados)
#df.groupby('Departamento').mean(numeric_only=True)
df_departamento = df.groupby('Departamento')['Salário'].mean()
df_departamento

Departamento
RH        2600.0
TI        4100.0
Vendas    3100.0
Name: Salário, dtype: float64

In [9]:
df_etanol = df_RJ.loc[df['Produto'] == 'ETANOL']
df_etanol = df.groupby('Bairro')['Valor de Venda'].mean().reset_index()
df_etanol

                    Bairro  Valor de Venda
0                    IGAPÓ        5.531176
1                        .        5.412381
2              13 DE JULHO        5.603704
3           15 DE NOVEMBRO        5.740000
4     1DISTRITO INDUSTRIAL        5.318857
...                    ...             ...
3991           ZOOBOTANICO        5.571392
3992                 ZUMBI        6.302500
3993    ZUMBI DOS PALMARES        6.392500
3994            ÁGUA VERDE        5.763418
3995                  ÉDEN        5.472258

[3996 rows x 2 columns]