In [1]:
import pandas as pd

In [2]:
df2_2024 = pd.read_csv('2_2024.csv', sep=';')
df1_2024 = pd.read_csv('ca-2024-01.csv', sep=';')
df2_2023 = pd.read_csv('ca-2023-02.csv', sep=';')
df1_2023 = pd.read_csv('ca-2023-01.csv', sep=';')
df2_2022 = pd.read_csv('ca-2022-02.csv', sep=';')
df1_2022 = pd.read_csv('ca-2022-01.csv', sep=';')
df2_2021 = pd.read_csv('ca-2021-02.csv', sep=';', encoding= 'latin1')
df1_2021 = pd.read_csv('ca-2021-01.csv', sep=';')
df2_2020 = pd.read_csv('ca-2020-02.csv', sep=';')
df1_2020 = pd.read_csv('ca-2020-01.csv', sep=';')

C:\Users\36134552025.2\AppData\Local\Temp\ipykernel_27212\1054907978.py:9: DtypeWarning: Columns (13) have mixed types. Specify dtype option on import or set low_memory=False.
  df2_2020 = pd.read_csv('ca-2020-02.csv', sep=';')

In [3]:
df = pd.concat([df2_2024,df1_2024,df2_2023,df1_2023,df2_2022,df1_2022,df2_2021, df1_2021, df2_2020, df1_2020])

In [4]:
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',','.').astype(float)

In [5]:
df['Data da Coleta'] = pd.to_datetime(df['Data da Coleta'], format= "%d/%m/%Y")

df['mes'] = df['Data da Coleta'].dt.month
df['ano'] = df['Data da Coleta'].dt.year

In [6]:
df_gasolina = df.loc[df['Produto'] == 'GASOLINA']
df_gasolina

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,mes,ano
0,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA,2024-07-01,6.790,NaN,R$ / litro,VIBRA,7,2024
5,N,AC,RIO BRANCO,AUTO POSTO CASTANHEIRA LTDA.,06.003.183/0001-85,ESTRADA DA FLORESTA,S/N,NaN,FLORESTA,69906-380,GASOLINA,2024-07-01,6.790,NaN,R$ / litro,EQUADOR,7,2024
10,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA,2024-07-01,6.990,NaN,R$ / litro,VIBRA,7,2024
14,N,AC,RIO BRANCO,AUTO POSTO ACAUAN LTDA,00.524.999/0001-78,RODOVIA AC 40,1800,NaN,VILA ACRE,69902-450,GASOLINA,2024-07-01,6.990,NaN,R$ / litro,VIBRA,7,2024
19,N,AC,RIO BRANCO,AUTO POSTO CANINDE LTDA,05.442.544/0001-27,RODOVIA AC 40,3206,KM 07,VILA ACRE,69902-450,GASOLINA,2024-07-01,6.980,NaN,R$ / litro,SABBÁ,7,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
496649,SE,SP,ARACATUBA,EDNEA FERREIRA RODRIGUES COMBUSTIVEIS,22.402.149/0001-30,RUA ANSELMO MANARELLI,533,NaN,SANTANA,16050-590,GASOLINA,2020-06-30,3.889,NaN,R$ / litro,BRANCA,6,2020
496651,N,PA,MARABA,POSTO 17 LTDA - ME,26.193.129/0001-57,QUADRA VINTE E NOVE (FL.17),S/N,LOTE 12,NOVA MARABA,68505-540,GASOLINA,2020-06-29,3.970,NaN,R$ / litro,BRANCA,6,2020
496653,N,AC,CRUZEIRO DO SUL,S & G PETROLEO LTDA,13.567.147/0002-90,ESTRADA DA VARIANTE,210,RURAL,MIRITIZAL,69980-000,GASOLINA,2020-06-29,4.739,NaN,R$ / litro,PETROBRAS DISTRIBUIDORA S.A.,6,2020
496657,SE,MG,SAO SEBASTIAO DO PARAISO,FC AUTO POSTO EIRELI,28.470.480/0001-73,AVENIDA ENGENHEIRO WASHINGTON MARTONI,1720,NaN,JARDIM PLANALTO,37950-000,GASOLINA,2020-06-29,4.548,"3,735",R$ / litro,BRANCA,6,2020
496661,SE,SP,SAO PAULO,CENTRO AUTOMOTIVO CENTER PAES DE BARROS LTDA,29.183.828/0001-04,AVENIDA PAES DE BARROS,2381,NaN,MOOCA,03115-001,GASOLINA,2020-06-30,3.699,NaN,R$ / litro,RAIZEN,6,2020

In [7]:
df_gasolina_media_regiao = df_gasolina.groupby(['mes','Estado - Sigla'])['Valor de Venda'].mean().reset_index()
df_gasolina_media_regiao

     mes Estado - Sigla  Valor de Venda
0      1             AC        5.959779
1      1             AL        5.406781
2      1             AM        5.423086
3      1             AP        4.746475
4      1             BA        5.538759
..   ...            ...             ...
319   12             RS        5.823997
320   12             SC        5.788383
321   12             SE        5.686107
322   12             SP        5.550808
323   12             TO        6.032574

[324 rows x 3 columns]

In [8]:
df_gasolina_adt = df.loc[df['Produto'] == 'GASOLINA ADITIVADA']
df_gasolina_adt

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira,mes,ano
1,N,AC,RIO BRANCO,CODEPE COMBUSTIVEIS LTDA,08.220.930/0001-62,RODOVIA BR-364 (RIO BRANCO-CRUZEIRO DO SUL) - ...,2755,LOTE 01/02/03/04/05 E 33,PORTAL DA AMAZONIA,69915-630,GASOLINA ADITIVADA,2024-07-01,6.840,NaN,R$ / litro,VIBRA,7,2024
6,N,AC,RIO BRANCO,AUTO POSTO CASTANHEIRA LTDA.,06.003.183/0001-85,ESTRADA DA FLORESTA,S/N,NaN,FLORESTA,69906-380,GASOLINA ADITIVADA,2024-07-01,6.890,NaN,R$ / litro,EQUADOR,7,2024
11,N,AC,RIO BRANCO,AUTO POSTO AMAPA - EIRELI,00.529.581/0001-53,VIA CHICO MENDES,3570,NaN,AREAL,69906-119,GASOLINA ADITIVADA,2024-07-01,7.090,NaN,R$ / litro,VIBRA,7,2024
15,N,AC,RIO BRANCO,AUTO POSTO ACAUAN LTDA,00.524.999/0001-78,RODOVIA AC 40,1800,NaN,VILA ACRE,69902-450,GASOLINA ADITIVADA,2024-07-01,6.990,NaN,R$ / litro,VIBRA,7,2024
20,N,AC,RIO BRANCO,AUTO POSTO CANINDE LTDA,05.442.544/0001-27,RODOVIA AC 40,3206,KM 07,VILA ACRE,69902-450,GASOLINA ADITIVADA,2024-07-01,7.140,NaN,R$ / litro,SABBÁ,7,2024
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
222610,SE,SP,SANTO ANDRE,AUTO POSTO IMPERADOR DE SANTO ANDRE LTDA,25.356.481/0001-01,AVENIDA PRESTES MAIA,3430,TERREO,VILA GUIOMAR,09071-000,GASOLINA ADITIVADA,2020-12-28,4.399,NaN,R$ / litro,IPIRANGA,12,2020
222615,SE,ES,VITORIA,POSTO DE COMBUSTIVEIS ILHA DO PRINCIPE LTDA,35.606.285/0001-93,AVENIDA NAIR AZEVEDO SILVA,220,NaN,ILHA DO PRINCIPE,29020-240,GASOLINA ADITIVADA,2020-12-28,4.240,NaN,R$ / litro,BRANCA,12,2020
222620,CO,MT,CUIABA,ALMEIDA JOSETTI E ALMEIDA JOSETTI LTDA,35.241.103/0001-28,AVENIDA CARMINDO DE CAMPOS,3100,NaN,DOM AQUINO,78015-021,GASOLINA ADITIVADA,2020-12-29,4.799,NaN,R$ / litro,IPIRANGA,12,2020
222626,SE,SP,ARACATUBA,POSTO UNI ICARAY LTDA,37.715.385/0001-83,AVENIDA JOAQUIM POMPEU DE TOLEDO,1631,NaN,ICARAY,16020-405,GASOLINA ADITIVADA,2020-12-28,4.599,NaN,R$ / litro,IPIRANGA,12,2020
222635,SE,RJ,RIO DE JANEIRO,AUTO POSTO REDE PARCEIRO ANIL LTDA,30.865.289/0001-72,AVENIDA TENENTE CORONEL MUNIZ DE ARAGAO,0,LOT ESCOLA PAL 30470,ANIL,22765-006,GASOLINA ADITIVADA,2020-12-29,5.199,NaN,R$ / litro,RAIZEN,12,2020

In [9]:
df_gasolina_adt_media = df_gasolina_adt.groupby(['Produto'])['Valor de Venda'].mean().reset_index()
df_gasolina_adt_media

              Produto  Valor de Venda
0  GASOLINA ADITIVADA        6.049328

In [10]:
df_gasolina_media = df_gasolina.groupby(['Produto'])['Valor de Venda'].mean().reset_index()
df_gasolina_media

    Produto  Valor de Venda
0  GASOLINA        5.600918

In [11]:
df_gasosa = pd.concat([df_gasolina_media,df_gasolina_adt_media])
df_gasosa

              Produto  Valor de Venda
0            GASOLINA        5.600918
0  GASOLINA ADITIVADA        6.049328

In [14]:
df_produto_media_ano = df_gasolina.groupby(['ano','Regiao - Sigla'])['Valor de Venda'].mean().reset_index()
df_produto_media_ano

     ano Regiao - Sigla  Valor de Venda
0   2020             CO        4.329780
1   2020              N        4.383790
2   2020             NE        4.337300
3   2020              S        4.187636
4   2020             SE        4.264024
5   2021             CO        6.048409
6   2021              N        5.939178
7   2021             NE        5.947638
8   2021              S        5.872317
9   2021             SE        5.834534
10  2022             CO        6.336670
11  2022              N        6.457659
12  2022             NE        6.554897
13  2022              S        6.194835
14  2022             SE        6.242079
15  2023             CO        5.473066
16  2023              N        5.917986
17  2023             NE        5.655570
18  2023              S        5.556938
19  2023             SE        5.415466
20  2024             CO        5.935224
21  2024              N        6.343645
22  2024             NE        6.022659
23  2024              S        5.984317
24  2024             SE        5.810284

In [16]:
bandeira = df_gasolina.groupby('Bandeira')['Valor de Venda'].mean().reset_index()
bandeira = bandeira.sort_values(by='Valor de Venda',ascending= False)
bandeira.head(5)

         Bandeira  Valor de Venda
37       PETRONAC        6.390000
55    SANTA LUCIA        6.159792
75    WALENDOWSKY        6.105462
31       ON PETRO        6.098584
74  VIBRA ENERGIA        6.087606

In [17]:
bandeira.tail(5)

       Bandeira  Valor de Venda
53        SAARA        4.363091
18      FEDERAL        4.116095
36     PETROLUZ        4.084600
21   GRAN PETRO        3.955970
48  RM PETROLEO        3.675000