In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('2º_2024.csv', sep= ';')
df['Valor de Venda'] = df['Valor de Venda'].str.replace(',','.').astype(float)

In [4]:
df_RJ = df.loc[(df['Estado - Sigla'] == 'RJ') & (df['Municipio'] == 'RIO DE JANEIRO')] # Acesso por condição
df_RJ

,Regiao - Sigla,Estado - Sigla,Municipio,Revenda,CNPJ da Revenda,Nome da Rua,Numero Rua,Complemento,Bairro,Cep,Produto,Data da Coleta,Valor de Venda,Valor de Compra,Unidade de Medida,Bandeira
1104,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARAJUBA LTDA,05.445.394/0001-05,ESTRADA DO MENDANHA,2745,NaN,CAMPO GRANDE,23092-001,GNV,01/07/2024,4.28,NaN,R$ / m³,BRANCA
1105,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARAJUBA LTDA,05.445.394/0001-05,ESTRADA DO MENDANHA,2745,NaN,CAMPO GRANDE,23092-001,GASOLINA,01/07/2024,5.39,NaN,R$ / litro,BRANCA
1106,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARAJUBA LTDA,05.445.394/0001-05,ESTRADA DO MENDANHA,2745,NaN,CAMPO GRANDE,23092-001,GASOLINA ADITIVADA,01/07/2024,5.42,NaN,R$ / litro,BRANCA
1107,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARAJUBA LTDA,05.445.394/0001-05,ESTRADA DO MENDANHA,2745,NaN,CAMPO GRANDE,23092-001,DIESEL S10,01/07/2024,5.79,NaN,R$ / litro,BRANCA
1108,SE,RJ,RIO DE JANEIRO,AUTO POSTO ARARAJUBA LTDA,05.445.394/0001-05,ESTRADA DO MENDANHA,2745,NaN,CAMPO GRANDE,23092-001,ETANOL,01/07/2024,3.99,NaN,R$ / litro,BRANCA
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
421239,SE,RJ,RIO DE JANEIRO,FLEMING - CENTRO DE COMERCIO E SERVICO LTDA,03.545.887/0001-91,AVENIDA AYRTON SENNA,0,CTR 2017.0009 LOT 98 E 99 NUM,BARRA DA TIJUCA,22775-002,GASOLINA,31/12/2024,5.89,NaN,R$ / litro,BRANCA
421240,SE,RJ,RIO DE JANEIRO,FLEMING - CENTRO DE COMERCIO E SERVICO LTDA,03.545.887/0001-91,AVENIDA AYRTON SENNA,0,CTR 2017.0009 LOT 98 E 99 NUM,BARRA DA TIJUCA,22775-002,GASOLINA ADITIVADA,31/12/2024,5.99,NaN,R$ / litro,BRANCA
421241,SE,RJ,RIO DE JANEIRO,FLEMING - CENTRO DE COMERCIO E SERVICO LTDA,03.545.887/0001-91,AVENIDA AYRTON SENNA,0,CTR 2017.0009 LOT 98 E 99 NUM,BARRA DA TIJUCA,22775-002,DIESEL,31/12/2024,5.89,NaN,R$ / litro,BRANCA
421242,SE,RJ,RIO DE JANEIRO,FLEMING - CENTRO DE COMERCIO E SERVICO LTDA,03.545.887/0001-91,AVENIDA AYRTON SENNA,0,CTR 2017.0009 LOT 98 E 99 NUM,BARRA DA TIJUCA,22775-002,DIESEL S10,31/12/2024,5.99,NaN,R$ / litro,BRANCA
421243,SE,RJ,RIO DE JANEIRO,FLEMING - CENTRO DE COMERCIO E SERVICO LTDA,03.545.887/0001-91,AVENIDA AYRTON SENNA,0,CTR 2017.0009 LOT 98 E 99 NUM,BARRA DA TIJUCA,22775-002,ETANOL,31/12/2024,4.39,NaN,R$ / litro,BRANCA

In [5]:
df_etanol = df_RJ.loc[df['Produto'] == 'ETANOL']

df_etanol_media_bairro = df_etanol.groupby('Bairro')['Valor de Venda'].mean().reset_index()
df_etanol_media_bairro = df_etanol_media_bairro.sort_values(by='Valor de Venda')

df_etanol_media_bairro.head(5)

            Bairro  Valor de Venda
49           ROCHA        3.934444
29  JARDIM SULACAP        3.950000
25          JACARE        3.990000
23           IRAJA        3.990000
48    RIO COMPRIDO        4.000000

In [6]:
df_etanol_media_bairro.tail(5)

             Bairro  Valor de Venda
21           GLORIA        4.690000
30            LAGOA        4.823333
28  JARDIM BOTANICO        4.838750
59   VARGEM PEQUENA        5.067778
19         FLAMENGO        5.689286

In [7]:
df_gasolina = df_RJ.loc[df['Produto'] == 'GASOLINA']
df_gasolina_media_bairro = df_gasolina.groupby('Bairro')['Valor de Venda'].mean().reset_index()
df_gasolina_media_bairro = df_gasolina_media_bairro.sort_values(by='Valor de Venda')

df_gasolina_media_bairro.head(5)

               Bairro  Valor de Venda
27             JACARE        5.390000
52              ROCHA        5.435556
31     JARDIM SULACAP        5.440000
46  QUINTINO BOCAIUVA        5.551111
35          MADUREIRA        5.566667

In [8]:
df_gasolina_media_bairro.tail(5)

             Bairro  Valor de Venda
32            LAGOA        6.456667
39  PARQUE FLAMENGO        6.530000
30  JARDIM BOTANICO        6.538750
62   VARGEM PEQUENA        6.634444
20         FLAMENGO        6.790000

In [10]:
df_diesel = df_RJ.loc[df['Produto'] == 'DIESEL']
df_dieses_media_bairro = df_diesel .groupby('Bairro')['Valor de Venda'].mean().reset_index()
df_dieses_media_bairro = df_dieses_media_bairro.sort_values(by='Valor de Venda')

df_dieses_media_bairro.head(5)

            Bairro  Valor de Venda
7   CIDADE DE DEUS        5.690000
4     BRAZ DE PINA        5.690000
11          JACARE        5.690000
3       BONSUCESSO        5.703158
20      SANTA CRUZ        5.756667

In [11]:
df_dieses_media_bairro.tail(5)

           Bairro  Valor de Venda
2         BENFICA        6.070000
12    JACAREPAGUA        6.117273
17          PENHA        6.212308
5            CAJU        6.390000
21  SAO CRISTOVAO        6.540000